name: Docker Image CI Dev

on:
  push:
    branches: [ dev/** ]
  pull_request:
    branches: [ dev/** ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.11
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: dschoen/bluelinky-docker
        tag-edge: true
        tag-latest: false
        tag-sha: true
    - uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        pull: true
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
